Elective/Areas/Teacher/Controllers/AddFacultativeController.cs
using BusinessModel;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// controller for creating 
    /// facultative by teacher
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Teacher)]
    public class AddFacultativeController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ITeacherService _teacherService;

        public AddFacultativeController(IAccountService accountService, ITeacherService teacherService)
        {
            _accountService = accountService;
            _teacherService = teacherService;
        }

        /// <summary>
        /// Dispay view model
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Creating new facultative for teacher
        /// </summary>
        /// <param name="model">view model</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(FacultativeViewModel model)
        {
            if (Request.HttpMethod == "POST")
            {
                if (ModelState.IsValid)
                {
                    Teacher teacher = _teacherService.GetTeacher(_accountService.GetAccount(User.Identity.Name));

                    _teacherService.AddFacultative(new Facultative(model.Name, model.Theme, model.Description
                        , model.Status
                        , teacher
                        , model.StartFacultative
                        , model.Duration), teacher);

                    return RedirectToAction("Index", "TeacherFacultative");
                }
            }

            return View(model);
        }
    }
}

Elective/Areas/Teacher/Views/AddFacultative/Index.cshtml
@model FacultativeViewModel
@using BusinessModel
@{
    ViewBag.Title = "Создать факультатив";
}
<div class="col-md-7 col-md-offset-2 fon-color">
    <h2 class="text-center">@ViewBag.Title</h2>
    <hr />
    @using (Html.BeginForm("Index", "AddFacultative", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <p> @Html.LabelFor(m => m.Name)</p>
        <p> @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = StringResource.FacultativeName })</p>
        <p>@Html.ValidationMessageFor(m => m.Name, "")</p>

        <p>@Html.LabelFor(m => m.Theme)</p>
        <p>@Html.TextBoxFor(m => m.Theme, new { @class = "form-control", @placeholder = StringResource.Theme })</p>
        <p>@Html.ValidationMessageFor(m => m.Theme, "")</p>

        <p>@Html.LabelFor(m => m.Duration)</p>
        <p>@Html.EditorFor(m => m.Duration)</p>
        <p>@Html.ValidationMessageFor(m => m.Duration, "")</p>

        <p>@Html.LabelFor(m => m.Description)</p>
        <p>@Html.TextBoxFor(m => m.Description, new { @class = "form-control", @placeholder = StringResource.Description})</p>
        <p>@Html.ValidationMessageFor(m => m.Description, "")</p>

        <p>@Html.LabelFor(m => m.StartFacultative)</p>
        @Html.TextBoxFor(m => m.StartFacultative, new { @placeholder = DateTime.Now.ToString("yyyy/MM/dd") })
        <p>@Html.ValidationMessageFor(m => m.StartFacultative, "")</p>

        <p>@Html.LabelFor(m => m.Status)</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Started) @FacultativeStatus.Started.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Registration) @FacultativeStatus.Registration.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.NotAvailable) @FacultativeStatus.NotAvailable.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Finished) @FacultativeStatus.Finished.ToString()</p>

        <input type="submit" value=@StringResource.Add class="btn btn-success text-right" />

        <br />
        <br />
    }

</div>