Elective/Areas/Admin/Controllers/AccountManagerController.cs
using Microsoft.AspNet.Identity.Owin;
using System.Web;
using System.Web.Mvc;
using BusinessModel;
using System;
using System.ComponentModel;
using System.Reflection;

namespace Elective
{
    /// <summary>
    /// Controller for diplaying
    /// all users in database
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Admin)]
    public class AccountManagerController : Controller
    {
        public ApplicationUserManager UserManager
        {
            get => HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
        }

        /// <summary>
        /// Displaying all users
        /// </summary>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }
    }
}

Elective/Areas/Admin/Controllers/LogsController.cs
using BusinessModel;
using System.Web.Mvc;

namespace Elective.Areas.Admin.Controllers
{
    /// <summary>
    /// Event log controller
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Admin)]
    public class LogsController : Controller
    {
        private IDefaultRepository<Log> _logRepository;

        public LogsController(IDefaultRepository<Log> logRepository)
        {
            _logRepository = logRepository;
        }

        /// <summary>
        /// Display event Log
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View(_logRepository.Get());
        }
    }
}

Elective/Controllers/MailController.cs
using BusinessModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// Mail controller
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize]
    public class MailController : Controller
    {
        private IAccountService _accountService;

        public MailController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        /// <summary>
        /// Page for send message "GET" http method
        /// </summary>
        /// <returns></returns>
        public ActionResult MailSend()
        {
            return View();
        }

        /// <summary>
        /// Send message action
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Send(MailViewModel model)
        {
            if (ModelState.IsValid)
            {
                _accountService.SendMessage(User.Identity.Name, model.Login, model.Theme, model.Message);

                return RedirectToAction("Index", "Message", new { type = "Info", message = "Отправлено" });
            }

            return View(model);
        }

        /// <summary>
        /// Return all receive messages for user 
        /// </summary>
        /// <returns></returns>
        public ActionResult MailReceive()
        {
            var messages = _accountService.GetAllMessages(User.Identity.Name).MessagesReceive;

            HttpContext.Cache.Insert(User.Identity.Name.ToLower(), messages.Where(s => s.Status == MessageState.NotRead).Count());

            return View(messages.OrderByDescending(s => s.SendDate).OfType<Message>().ToList());
        }

        /// <summary>
        /// Return select receieve message
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult MailOptionR(Guid id)
        {
            bool notRead = false;

            Message message = _accountService.GetMessageReceive(User.Identity.Name, id, ref notRead);

            if (notRead)
                HttpContext.Cache.Insert(User.Identity.Name, (int)HttpContext.Cache.Get(User.Identity.Name) - 1);

            return View("MailOption", message);
        }

        /// <summary>
        /// Return select send message
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult MailOptionS(Guid id)
        {
            return View("MailOption", _accountService.GetMessageSend(User.Identity.Name, id));
        }

        /// <summary>
        /// Return all user send out messages
        /// </summary>
        /// <returns></returns>
        public ActionResult MailSendOut()
        {
            return View(_accountService.GetAllMessages(User.Identity.Name)
                .MessageSend.OrderByDescending(s => s.SendDate).OfType<Message>().ToList());
        }

    }
}

Elective/Controllers/PersonalAreaController.cs
using BusinessModel;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// Controller for working 
    /// with personal data
    /// </summary>
    [Authorize]
    [ErrorExeptionFilter]
    public class PersonalAreaController : Controller
    {
        private IAccountService _accountService;

        public PersonalAreaController(IAccountService accountService)
        {
            _accountService = accountService;
        }


        /// <summary>
        /// Displaying personal data
        /// </summary>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index()
        {
            return View(_accountService.GetAccount(User.Identity.Name));
        }

        public ActionResult Edit()
        {
            return View();
        }

        /// <summary>
        /// Edit personal data
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(PersonViewModel personVM)
        {
            if (Request.HttpMethod == "POST")
            {
                Account account = _accountService.GetAccount(User.Identity.Name);

                foreach (var arg1 in account.GetType().GetProperties())
                {
                    foreach (var arg2 in personVM.GetType().GetProperties())
                    {
                        if (ModelState.IsValidField(arg1.Name) && arg1.Name == arg2.Name)
                        {
                            arg1.SetValue(account, arg2.GetValue(personVM));
                        }
                    }
                }

                _accountService.ChangeStateEntity(account);

                return RedirectToAction("Index");
            }
            return View(personVM);
        }
    }
}

Elective/Views/Shared/_Layout.cshtml
@using BusinessModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Layout/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

</head>

@helper ButtonDrop(string role, IEnumerable<MvcHtmlString> options, string style)
    {
        <li class="dropdown">
            <a href="#" class="dropdown-toggle @style" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@role <span class="caret"></span></a>
            <ul class="dropdown-menu">
                @foreach (var item in options)
                {
                    <li role="separator" class="divider"></li>
                    <li>@item</li>
                }
            </ul>
        </li>
}

<body>
    <header class="page-header">
        <img class="brand" src="~/Content/Brand.png">
    </header>

    <br />
    <br />
    <br />
    <br />

    <div class="main inline">
        <div class="content">
            <p class="levp"><img class="lev" src="~/Content/Lev.png"></p>
            <nav class="menu navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">Elective ♥</a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink(StringResource.Main, "Index", "Home", new { Area = "" }, null)</li>

                            @if (User.IsInRole(Role.Admin))
                            {

                                @ButtonDrop(StringResource.Admin, new List<MvcHtmlString> {
                                @Html.ActionLink(StringResource.AllUsers, "Index", "AccountManager", new { Area = "Admin" }, null),
                                @Html.ActionLink(StringResource.RegTeacher, "Index", "RegisterTeacher", new { Area = "Admin" }, null),
                                @Html.ActionLink(StringResource.Log, "Index", "Logs", new { Area = "Admin" }, null)
                                }, "");
                            }

                            @if (User.IsInRole(Role.Student))
                            {

                                @ButtonDrop(StringResource.Student, new List<MvcHtmlString> {
                                @Html.ActionLink(StringResource.AllElective, "Index", "StudentManager", new { Area = "Student" }, null),
                                @Html.ActionLink(StringResource.MyElective, "Index", "StudentFacultatives", new { Area = "Student" }, null)
                                }, "");
                            }

                            @if (User.IsInRole(Role.Teacher))
                            {

                                @ButtonDrop(StringResource.Teacher, new List<MvcHtmlString> {
                                @Html.ActionLink(StringResource.MyElective, "Index", "TeacherFacultative", new { Area = "Teacher" }, null),
                                @Html.ActionLink(StringResource.CreateElective, "Index", "AddFacultative", new { Area = "Teacher" }, null)
                                }, "");
                            }
                            <li>@Html.ActionLink(StringResource.Contact, "Contact", "Home", new { Area = "" }, null)</li>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>@Html.ActionLink(" Login", "Login", "Account", new { Area = "" }, new { @class = "glyphicon glyphicon-log-in" })</li>
                                <li>@Html.ActionLink(" Sign UP", "Register", "Account", new { Area = "" }, new { @class = "glyphicon glyphicon-user" })</li>
                            }
                            else
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle glyphicon glyphicon-user" data-toggle="dropdown" 
                                       role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name.Insert(0, " ") 
                                    <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li role="separator" class="divider"></li>
                                        <li>@Html.ActionLink(StringResource.Profile, "Index", "PersonalArea", new { Area = "" }, null)</li>
                                        <li role="separator" class="divider"></li>
                                        <li>@Html.ActionLink(StringResource.WriteMessage, "MailSend", "Mail", new { Area = "" }, null)</li>
                                        <li role="separator" class="divider"></li>
                                        <li>
                                            <a href="@Url.Action("MailReceive", "Mail", new { Area = "" }, null)">
                                                @StringResource.MessageReceive
                                                <span class='badge' style='background-color:blue'>
                                                    @if (Cache.Get(User.Identity.Name.ToLower()) != null)
                                                    {
                                                        @Cache.Get(User.Identity.Name.ToLower()).ToString();
                                                    }
                                                    else
                                                    { <span>0</span>}
                                                </span>
                                            </a>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li>@Html.ActionLink(StringResource.MessageSend, "MailSendOut", "Mail", new { Area = "" }, null)</li>
                                    </ul>
                                </li>
                                <li>@Html.ActionLink(StringResource.SignOut, "LogOff", "Account", new { Area = "" }, new { @class = "glyphicon glyphicon-log-out" })</li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
            @RenderBody()
        </div>
    </div>

    <footer>
        <hr />
        <p class="text-right">&copy; Parviz Musaiev</p>
    </footer>
</body>
</html>