Elective/Areas/Student/Controllers/StudentFacultativeController.cs
using BusinessModel;
using System;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// Controller for displaying select facultative
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Student)]
    public class StudentFacultativeController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentFacultativeController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        /// <summary>
        /// displaying select facultative
        /// </summary>
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index(Guid id)
        {
            return View(_studentService.GetFacultative(new Facultative() { Id = id }));
        }
    }
}

Elective/Areas/Student/Controllers/StudentFacultativesController.cs
using BusinessModel;
using System.Linq;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// Controller for displaying all register facultatives
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Student)]
    public class StudentFacultativesController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IStudentService _studentService;

        public StudentFacultativesController(IAccountService accountService, IStudentService studentService)
        {
            _accountService = accountService;
            _studentService = studentService;
        }

        /// <summary>
        /// Displaying all register facultatives
        /// </summary>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index()
        {
            Account account = _accountService.GetAccount(User.Identity.Name);
            Student student = _studentService.GetStudent(account);

            return View(student.RegistrFacultatives.OrderBy(s => s.Status));
        }
    }
}

Elective/Areas/Student/Views/StudentFacultatives/Index.cshtml
@using BusinessModel
@{
    ViewBag.Title = "Мои факультативы";
}
@model IEnumerable<Facultative>


@helper Facultatives(Facultative facultative, string style)
{
    <div class='@style'>
        <h3 class="text-center">@facultative.Name</h3>
        <p>Тема: @facultative.Theme</p>
        <p>Статус: @facultative.Status</p>
        <p>Количество зарегистрированных: @facultative.Audience.Count</p>
        <p class="text-right">@Html.ActionLink("Посмотреть", "Index", "StudentFacultative", new { id = facultative.Id }, new { @class = "btn btn-warning btn-lg text-danger" })</p>
    </div>
}

<div class=" col-lg-12 person-color">
    <h2 class="text-center">@ViewBag.Title</h2>
    <br />

    <div class="facultative-label label-default text-balck">
        <br />
        @foreach (var item in Model)
        {
            <div class="facultative-label">
                @if (item.Status == FacultativeStatus.Registration)
                {
                    @Facultatives(item, "label-success facultative-label text-dark");
                }
                @if (item.Status == FacultativeStatus.Started)
                {
                    @Facultatives(item, "label-warning facultative-label text-dark");
                }
                @if (item.Status == FacultativeStatus.Finished)
                {
                    @Facultatives(item, "label-info facultative-label");
                }
                @if (item.Status == FacultativeStatus.NotAvailable)
                {
                    @Facultatives(item, "label-danger facultative-label text-dark");
                }

            </div>
            <br />
            <br />
        }

    </div>
    <br />
    <br />
</div>