Elective/Areas/Teacher/Controllers/EditFacultativeController.cs
using BusinessModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Elective
{
    /// <summary>
    /// Controler for editing 
    /// facultative by teacher
    /// </summary>
    [ErrorExeptionFilter]
    [Authorize(Roles = Role.Teacher)]
    public class EditFacultativeController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ITeacherService _teacherService;

        public EditFacultativeController(IAccountService accountService, ITeacherService teacherService)
        {
            _accountService = accountService;
            _teacherService = teacherService;
        }

        /// <summary>
        /// View form
        /// </summary>
        public ActionResult Index(Guid id)
        {
            return View();
        }


        /// <summary>
        /// Creating facultative
        /// </summary>
        [HttpPost]
        public ActionResult Index(FacultativeViewModel facultativeVM, Guid id, string button)
        {
            var teacher = _teacherService.GetTeacher(_accountService.GetAccount(User.Identity.Name));
            var facultative = teacher.MyFacultatives.Where(s => s.Id == id).FirstOrDefault();
            facultative = _teacherService.GetFacultative(facultative);

            if (Request.HttpMethod == "POST")
            {

                if (button == "Change")
                {
                    foreach (var arg1 in facultative.GetType().GetProperties())
                    {
                        foreach (var arg2 in facultativeVM.GetType().GetProperties())
                        {
                            if (ModelState.IsValidField(arg1.Name) && arg1.Name == arg2.Name)
                            {
                                arg1.SetValue(facultative, arg2.GetValue(facultativeVM));
                            }
                        }
                    }
                    _teacherService.ChangeStateEntity(facultative);

                    return RedirectToAction("Index", "TeacherFacultative");
                }
                if (button == "Delete")
                {
                    _teacherService.DeleteFacultative(facultative);

                    return RedirectToAction("Index", "TeacherFacultative");
                }
            }

            return View(facultativeVM);
        }
    }
}

Elective/Areas/Teacher/Views/EditFacultative/Index.cshtml
@using BusinessModel
@{
    ViewBag.Title = "Редактировать факультатив";
}
@{Html.EnableClientValidation(false);}
@model FacultativeViewModel



<div class="col-md-7 col-md-offset-2 fon-color">
    <h2 class=" text-center">@ViewBag.Title</h2>

    @using (Html.BeginForm("Index", "EditFacultative", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <p> @Html.LabelFor(m => m.Name)</p>
        <p> @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = StringResource.FacultativeName })</p>
        <p>@Html.ValidationMessageFor(m => m.Name, "")</p>

        <p>@Html.LabelFor(m => m.Theme)</p>
        <p>@Html.TextBoxFor(m => m.Theme, new { @class = "form-control", @placeholder = StringResource.Theme })</p>
        <p>@Html.ValidationMessageFor(m => m.Theme, "")</p>

        <p>@Html.LabelFor(m => m.Duration)</p>
        <p>@Html.EditorFor(m => m.Duration)</p>
        <p>@Html.ValidationMessageFor(m => m.Duration, "")</p>

        <p>@Html.LabelFor(m => m.Description)</p>
        <p>@Html.TextBoxFor(m => m.Description, new { @class = "form-control", @placeholder = StringResource.Description })</p>
        <p>@Html.ValidationMessageFor(m => m.Description, "")</p>

        <p>@Html.LabelFor(m => m.StartFacultative)</p>
        <p>@Html.TextBoxFor(m => m.StartFacultative, new { @placeholder = DateTime.Now.ToString("yyyy/MM/dd") })</p>
        <p>@Html.ValidationMessageFor(m => m.StartFacultative, "")</p>

        <p>@Html.LabelFor(m => m.Status)</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Started) @FacultativeStatus.Started.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Registration) @FacultativeStatus.Registration.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.NotAvailable) @FacultativeStatus.NotAvailable.ToString()</p>
        <p>@Html.RadioButtonFor(m => m.Status, FacultativeStatus.Finished) @FacultativeStatus.Finished.ToString()</p>

        <div class="btn-group">
            <button type="submit" class="btn btn-primary" name="button" value="Change">@StringResource.ChangeDate</button>
            <button type="submit" class="btn btn-primary" name="button" value="Delete">@StringResource.Delete</button>
        </div>

        <br />
        <br />
    }
</div>